// Temp fix for the Generated config file 

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY!
// Generated by CMake on @CMAKE_GENERATOR@ @CMAKE_SYSTEM_NAME@ at @CURRENT_TIME@ UTC
// To modify the values, update the CMake configuration or the template config.hpp.in

#pragma once
#include <cstdint>

namespace config {
    /*
    This header file defines const that are execute at compile time
    To modify the values of these constants look in the main Cmake file
    */

    // Network inbound
    inline constexpr uint32_t NETWORK_INBOUND_PORT_NUMBER = 11000;
    inline constexpr uint8_t NETWORK_INBOUND_THREAD_COUNT = 4;

    // Network outbound
    inline constexpr uint32_t NETWORK_OUTBOUND_PORT_NUMBER = 12000;
    inline constexpr uint8_t NETWORK_OUTBOUND_THREAD_COUNT = 4;

    // Ring buffer
    inline constexpr uint32_t RING_BUFFER_SIZE = 1024;

    // Ring buffer number of consumers
    inline constexpr uint8_t NUM_CONSUMERS = 2;
}
